import React from 'react';
import { motion } from 'framer-motion';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from '@/components/ui/card';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { CheckCircle, Zap, Users, BarChart, BookOpen, ShieldCheck, Star, Brain, Rocket, UserPlus, BookOpenText, PlayCircle, Sparkles } from 'lucide-react';
import { Link } from 'react-router-dom';
import OnboardingLearningStyle from '@/components/OnboardingLearningStyle';

const fadeIn = (direction = 'up', delay = 0) => ({
  hidden: { opacity: 0, y: direction === 'up' ? 20 : direction === 'down' ? -20 : 0, x: direction === 'left' ? 20 : direction === 'right' ? -20 : 0 },
  visible: { opacity: 1, y: 0, x: 0, transition: { duration: 0.6, delay, ease: 'easeOut' } },
});

const staggerContainer = (staggerChildren = 0.1, delayChildren = 0) => ({
  hidden: { opacity: 0 },
  visible: { opacity: 1, transition: { staggerChildren, delayChildren } },
});

const features = [
  { icon: Brain, title: "AI-Powered Lessons", description: "Engaging, adaptive lessons tailored to your child's pace and grade level, generated by advanced AI." },
  { icon: Zap, title: "Interactive Content", description: "Quizzes, activities, and multimedia to make learning fun and effective." },
  { icon: BarChart, title: "Progress Tracking", description: "Visual progress reports and mastery tracking for parents and students." },
  { icon: Users, title: "Multi-Student Ready", description: "Manage multiple children under one parent account with ease." },
  { icon: BookOpen, title: "Comprehensive Subjects", description: "Covering Math, Reading, Science, History, Art, Coding, and more!" },
  { icon: ShieldCheck, title: "Safe & Secure", description: "A COPPA-compliant platform focused on your child's safety." },
];

const pricingTiers = [
  { name: "Spark Learner", price: "$19", period: "/month", features: ["1 Student Profile", "Access to All Core Subjects", "AI Lesson Generation", "Basic Progress Tracking", "Email Support"], cta: "Get Started", popular: false, color: "smartSchool-blue" },
  { name: "Genius Explorer", price: "$39", period: "/month", features: ["Up to 3 Student Profiles", "All Core & Elective Subjects", "Advanced AI Personalization", "Detailed Progress Reports", "Printable Worksheets", "Priority Email Support"], cta: "Choose Genius", popular: true, color: "smartSchool-red" },
  { name: "Scholar Pro", price: "$349", period: "/year", features: ["Up to 5 Student Profiles", "Everything in Genius Explorer", "Dedicated Onboarding Call", "Early Access to New Features", "Community Forum Access"], cta: "Go Scholar", popular: false, color: "smartSchool-yellow" },
];

const faqs = [
  { q: "What grade levels does SmartSchool AI cover?", a: "SmartSchool AI is designed for Pre-K through 12th grade, with adaptive content for each level." },
  { q: "Is SmartSchool AI aligned with educational standards?", a: "Yes, our AI strives to align lessons with Common Core and other state standards to ensure comprehensive coverage." },
  { q: "Can I try SmartSchool AI before subscribing?", a: "We plan to offer a trial period or limited free content in the future. Currently, you can explore our features and sign up for a plan." },
  { q: "How does the AI adapt to my child's learning?", a: "Our AI analyzes your child's responses to quizzes and activities, adjusting the difficulty and focus of subsequent lessons to match their needs." },
];

const LandingPage = () => {
  const [showQuiz, setShowQuiz] = React.useState(false);
  const [quizResult, setQuizResult] = React.useState(null);

  return (
    <motion.div className="overflow-x-hidden animate-fade-in" initial="hidden" animate="visible" variants={staggerContainer()}>
      {/* Hero Section */}
      <motion.section
        variants={fadeIn('up')}
        className="relative py-20 md:py-32 bg-gradient-to-b from-smartSchool-blue via-blue-400 to-white text-white overflow-hidden"
      >
        {/* Logo at top center */}
        <div className="flex justify-center mb-8">
          <img src="/images/logo12.png" alt="SmartSchool AI Logo" className="h-24 w-24 rounded bg-white p-2 shadow-lg" />
        </div>
        {/* Decorative blue shapes */}
        <div className="absolute -top-24 -left-24 w-96 h-96 bg-smartSchool-blue opacity-30 rounded-full blur-3xl z-0" />
        <div className="absolute -bottom-32 right-0 w-96 h-96 bg-blue-300 opacity-20 rounded-full blur-2xl z-0" />
        <div className="absolute inset-0 opacity-10 z-0">
          <img alt="Abstract background learning pattern" className="w-full h-full object-cover animate-float" src="https://images.unsplash.com/photo-1700941019917-731dc64ce685" />
        </div>
        <div className="container mx-auto px-6 text-center relative z-10">
          <motion.h1 variants={fadeIn('down', 0.2)} className="text-4xl sm:text-5xl md:text-6xl font-extrabold mb-6 leading-tight text-white drop-shadow-lg">
            The Future of Homeschooling is Here.
          </motion.h1>
          <motion.p variants={fadeIn('up', 0.4)} className="text-lg md:text-xl mb-10 max-w-3xl mx-auto font-openSans text-blue-100">
            SmartSchool AI provides personalized, AI-powered education for Pre-K to 12th grade, making learning engaging, effective, and fun for your child.
          </motion.p>
          <motion.div variants={fadeIn('up', 0.6)}>
            <Link to="/signup">
              <Button size="lg" className="bg-smartSchool-yellow hover:bg-yellow-500 text-smartSchool-blue font-bold py-4 px-10 text-xl shadow-lg transform hover:scale-105 transition-transform duration-200 rounded-xl">
                <Rocket size={24} className="mr-3 animate-wiggle hover:animate-wiggle" /> Get Started For Free
              </Button>
            </Link>
          </motion.div>
          <div className="mt-10 flex flex-col items-center">
            <Button size="lg" className="mb-4" onClick={() => setShowQuiz(true)}>
              Take the Learning Style Quiz
            </Button>
            {quizResult && (
              <div className="mt-4 p-4 bg-white text-smartSchool-blue rounded shadow">
                Your learning style: <b className="capitalize">{quizResult}</b>
              </div>
            )}
          </div>
        </div>
        {showQuiz && (
          <div className="fixed inset-0 bg-black bg-opacity-40 flex items-center justify-center z-50">
            <div className="bg-white rounded-lg shadow-lg p-6 max-w-lg w-full relative">
              <button className="absolute top-2 right-2 text-gray-400 hover:text-gray-700" onClick={() => setShowQuiz(false)}>&times;</button>
              <OnboardingLearningStyle onComplete={(style) => { setQuizResult(style); setShowQuiz(false); }} />
            </div>
          </div>
        )}
      </motion.section>

      {/* Features Section */}
      <motion.section className="py-16 md:py-24 bg-slate-50" variants={staggerContainer(0.2, 0.5)}>
        <div className="container mx-auto px-6">
          <motion.h2 variants={fadeIn('up')} className="text-3xl md:text-4xl font-bold text-center mb-4 text-gray-800">Why Choose <span className="text-smartSchool-blue">SmartSchool AI</span>?</motion.h2>
          <motion.p variants={fadeIn('up', 0.1)} className="text-center text-gray-600 mb-12 md:mb-16 max-w-2xl mx-auto font-openSans">
            We combine cutting-edge AI with proven educational strategies to create a learning experience your child will love.
          </motion.p>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((feature, index) => (
              <motion.div key={index} variants={fadeIn('up', index * 0.1)}>
                <Card className="h-full shadow-lg hover:shadow-xl transition-shadow duration-300 rounded-2xl border-2 border-smartSchool-yellow bg-white hover:border-smartSchool-blue/80 hover:scale-[1.03] hover:-translate-y-1 hover:bg-blue-50 group cursor-pointer">
                  <CardHeader className="pb-4">
                    <div className="flex items-center space-x-3">
                      <span className="rounded-full p-2 bg-gradient-to-br from-smartSchool-blue via-smartSchool-yellow to-smartSchool-red shadow group-hover:scale-110 transition-transform">
                        <feature.icon className="w-10 h-10 text-smartSchool-blue group-hover:text-smartSchool-red transition-colors duration-200" />
                      </span>
                      <CardTitle className="text-xl font-semibold text-smartSchool-blue group-hover:text-smartSchool-red transition-colors">{feature.title}</CardTitle>
                    </div>
                  </CardHeader>
                  <CardContent>
                    <p className="text-gray-600 font-openSans text-sm">{feature.description}</p>
                  </CardContent>
                </Card>
              </motion.div>
            ))}
          </div>
        </div>
      </motion.section>
      
      {/* How It Works Section */}
      <motion.section className="py-16 md:py-24 bg-gradient-to-b from-smartSchool-blue via-blue-100 to-white" variants={staggerContainer()}>
        <div className="container mx-auto px-6">
          <motion.h2 variants={fadeIn('up')} className="text-3xl md:text-4xl font-bold text-center mb-16 text-white drop-shadow-lg">
            Getting Started is <span className="text-smartSchool-yellow">Easy!</span>
          </motion.h2>
          <div className="grid md:grid-cols-3 gap-10 text-center">
            {[
              { icon: UserPlus, title: "Sign Up", description: "Create your parent account and add student profiles in minutes." },
              { icon: BookOpenText, title: "Choose Subjects", description: "Select from a wide range of subjects tailored to your child's grade." },
              { icon: PlayCircle, title: "Start Learning!", description: "Let your child dive into interactive AI-generated lessons and watch them grow." }
            ].map((step, index) => (
              <motion.div key={index} variants={fadeIn('up', index * 0.2)} className="flex flex-col items-center">
                <div className="bg-white p-5 rounded-full mb-6 shadow-lg border-4 border-smartSchool-blue">
                  <step.icon className="w-12 h-12 text-smartSchool-blue" />
                </div>
                <h3 className="text-xl font-semibold mb-2 text-smartSchool-blue">{step.title}</h3>
                <p className="text-gray-700 font-openSans text-sm">{step.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </motion.section>

      {/* Pricing Section */}
      <motion.section id="pricing" className="py-16 md:py-24 bg-gray-100" variants={staggerContainer()}>
        <div className="container mx-auto px-6">
          <motion.h2 variants={fadeIn('up')} className="text-3xl md:text-4xl font-bold text-center mb-4 text-gray-800">Flexible Plans for Every Family</motion.h2>
          <motion.p variants={fadeIn('up', 0.1)} className="text-center text-gray-600 mb-12 md:mb-16 max-w-2xl mx-auto font-openSans">
            Choose the plan that best fits your homeschooling needs and budget. All plans come with our core AI learning engine.
          </motion.p>
          <div className="grid lg:grid-cols-3 gap-8 items-stretch">
            {pricingTiers.map((tier, index) => (
              <motion.div key={index} variants={fadeIn('up', index * 0.15)} className="flex">
                <Card className={`w-full flex flex-col rounded-2xl shadow-xl ${tier.popular ? 'border-4 border-smartSchool-red transform scale-105' : 'border border-gray-200'} transition-all duration-300`}>
                  {tier.popular && <div className="bg-smartSchool-red text-white text-xs font-bold uppercase tracking-wider py-1 px-4 rounded-t-lg text-center -mt-px">Most Popular</div>}
                  <CardHeader className="text-center pt-8 pb-4">
                    <CardTitle className={`text-2xl font-bold text-${tier.color}`}>{tier.name}</CardTitle>
                    <div className="my-4">
                      <span className="text-5xl font-extrabold text-gray-800">{tier.price}</span>
                      <span className="text-gray-500 font-openSans">{tier.period}</span>
                    </div>
                  </CardHeader>
                  <CardContent className="flex-grow">
                    <ul className="space-y-3 mb-8">
                      {tier.features.map((feature, fIndex) => (
                        <li key={fIndex} className="flex items-start">
                          <CheckCircle className="w-5 h-5 text-green-500 mr-2 mt-0.5 flex-shrink-0" />
                          <span className="text-gray-600 font-openSans text-sm">{feature}</span>
                        </li>
                      ))}
                    </ul>
                  </CardContent>
                  <CardFooter className="p-6 mt-auto">
                    <Link to="/signup" className="w-full">
                      <Button size="lg" className={`w-full font-bold py-3 text-lg rounded-xl bg-${tier.color} hover:bg-${tier.color}/90 text-white`}>
                        {tier.cta}
                      </Button>
                    </Link>
                  </CardFooter>
                </Card>
              </motion.div>
            ))}
          </div>
        </div>
      </motion.section>

      {/* FAQ Section */}
      <motion.section className="py-16 md:py-24 bg-gradient-to-b from-smartSchool-blue via-blue-100 to-white" variants={staggerContainer()}>
        <div className="container mx-auto px-6">
          <motion.h2 variants={fadeIn('up')} className="text-3xl md:text-4xl font-bold text-center mb-4 text-white drop-shadow-lg">
            Frequently Asked Questions
          </motion.h2>
          <motion.div variants={fadeIn('up', 0.2)} className="max-w-3xl mx-auto">
            <Accordion type="single" collapsible className="w-full">
              {faqs.map((faq, index) => (
                <AccordionItem value={`item-${index}`} key={index} className="border-b border-gray-200">
                  <AccordionTrigger className="py-5 text-left text-lg font-semibold text-gray-700 hover:text-smartSchool-blue hover:no-underline">
                    {faq.q}
                  </AccordionTrigger>
                  <AccordionContent className="pb-5 pt-2 text-gray-600 font-openSans text-base">
                    {faq.a}
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          </motion.div>
        </div>
      </motion.section>

      {/* Call to Action Section */}
      <motion.section className="py-20 md:py-32 bg-yellow-100 text-gray-800" variants={fadeIn('up')}>
        <div className="container mx-auto px-6 text-center">
          <motion.h2 variants={fadeIn('up', 0.1)} className="text-3xl sm:text-4xl md:text-5xl font-extrabold mb-6">
            Ready to Transform Your Child's Education?
          </motion.h2>
          <motion.p variants={fadeIn('up', 0.2)} className="text-lg md:text-xl mb-10 max-w-2xl mx-auto font-openSans">
            Join thousands of families discovering the joy of personalized, AI-driven learning with SmartSchool AI.
          </motion.p>
          <motion.div variants={fadeIn('up', 0.3)}>
            <Link to="/signup">
              <Button size="lg" className="bg-smartSchool-red hover:bg-red-700 text-white font-bold py-4 px-10 text-xl shadow-lg transform hover:scale-105 transition-transform duration-200 rounded-xl">
                <Star size={24} className="mr-3" /> Sign Up & Start Learning
              </Button>
            </Link>
          </motion.div>
        </div>
      </motion.section>

      {/* Floating helper button */}
      <div className="fixed bottom-6 right-6 z-50 group">
        <button className="bg-smartSchool-blue text-white rounded-full shadow-lg p-4 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-yellow-400 animate-float relative">
          <span className="sr-only">Need help?</span>
          <Sparkles className="w-6 h-6 animate-wiggle group-hover:animate-wiggle" />
        </button>
        <div className="absolute right-16 bottom-1/2 translate-y-1/2 bg-white text-gray-700 px-4 py-2 rounded shadow-lg opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none group-hover:pointer-events-auto">
          Need help? Click here for tips!
        </div>
      </div>
    </motion.div>
  );
};

export default LandingPage;